---
title: "Annual Summary"
author: "NYS Department of Environmental Conservation"
date: "`r format(Sys.Date(),format='%B %d, %Y')`"
output:  
  html_document:
    toc: true
    toc_depth: 6
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##Thresholds
These are the thresholds I used to calculate the assessments below  
```{r, echo=FALSE, results='asis'}
library(DT)
DT::datatable(thresholds, options = list(scrollX = TRUE,columnDefs = list(list(className = 'dt-center', targets = 0:5))))
```

##Assessments
```{r, echo=FALSE, results='asis'}
library(DT)
DT::datatable(trendsimple, options = list(scrollX = TRUE))
```

##Data supporting Assessments
```{r, echo=FALSE, results='asis'}
library(DT)
DT::datatable(trend, options = list(scrollX = TRUE))
```

##Depth profiles
```{r, echo=FALSE, results='asis'}
profile<-data[data$INFO_TYPE=="DP",]
profile<-unique(profile[c('LAKE_ID','WATER','LOCATION_ID','Characteristic.Name','Depth','Result.Value','SAMPLE_DATE')])
profile$Characteristic.Name[profile$Characteristic.Name==""] <- NA
profile<-profile[!is.na(profile$Characteristic.Name),]
#restrict to only the parameters that should be in a profile
profile<-profile[profile$Characteristic.Name=="DISSOLVED OXYGEN (DO)"|
                 profile$Characteristic.Name=="OXIDATION REDUCTION POTENTIAL (ORP)"|
                 profile$Characteristic.Name=="PH"|
                 profile$Characteristic.Name=="SPECIFIC CONDUCTANCE"|
                 profile$Characteristic.Name=="TEMPERATURE, WATER"|
                 profile$Characteristic.Name=="DISSOLVED OXYGEN SATURATION",]

lakes<-unique(profile$LAKE_ID)
nlakes<-length(lakes)

for(i in 1:nlakes){
temp<-profile[profile$LAKE_ID==lakes[i],]
display<-unique(temp$LAKE_ID)
display<-paste("  \n","###",display,"  \n",sep="")
cat(display)

if((length(temp$Result.Value))!=0){
library(ggplot2)
library(gridExtra)
params<-unique(temp$Characteristic.Name)
nparams<-length(params)
p<-list()
for(j in 1:nparams){
  temp1<-temp[temp$Characteristic.Name==params[j],]
  temp1<-temp1[!is.na(temp1$Characteristic.Name),]
  if((length(temp1$Result.Value))!=0){
  temp1<-temp1[order(temp1$SAMPLE_DATE,temp1$Depth),]
  temp1$SAMPLE_DATE<-format(temp1$SAMPLE_DATE,"%Y.%m.%d")
  temp1$SAMPLE_DATE<-factor(temp1$SAMPLE_DATE,unique(temp1$SAMPLE_DATE))
  p[[j]]<-(ggplot(temp1[order(temp1$Depth,temp1$SAMPLE_DATE),],aes(Result.Value,Depth)) +
    geom_point() +
    geom_path(aes(color=factor(SAMPLE_DATE))) +
    scale_y_reverse(lim = c((max(temp$Depth)+0.25),0)) +
    theme(axis.title.x = element_blank()) +
    labs(title=params[j], y="Depth (m)",colour = "")) 
  }
  rm(list=c('temp1'))
}

do.call(grid.arrange,c(p,ncol=2))
cat("  \n")
cat("  \n")
}
rm(list=c('temp','j','params','nparams','p','display'))
}
rm(list=c('i','lakes','nlakes'))
```
